### ISSUE TITLE
what's the difference between react-nil and this

### ISSUE THREAD

**Issue by azl397985856** [react-spring/react-nil#2]
what's the difference between react-nil and this:

```js
import React from 'react'
import ReactDOM from 'react-dom'

function UseFriendStatus(friendID) {
  console.log('21212121')
  return null
}

ReactDOM.render(<UseFriendStatus />, document.getElementById('root'))
```

return null is a valid case

**Comment by drcmda** [comment]
react-dom doesn't work on node afaik, otherwise there is no difference. react-nil does nothing but allow react to run in smallest possible setup, without native elements (div, span, mesh, box, group, view, image ...). it's 20kb packed up.

**Comment by Ketcap** [comment]
Another question related to that returning empty fragments are working as well why not that but null ? 
```
const Component = ()=>{
   return <></>
}
```

**Comment by drcmda** [comment]
yes, you could.

even that works:

```jsx
return <marmalade />
```

because it ignores native elements. `null` is shorter and it's a legitimate return value in react.

**Comment by Ketcap** [comment]
So `<></>` is not a legitimate return value you are saying ? I'll return the empty component instead null. I don't see the difference. I'm trying to understand. I understand this usage that doesn't want to return component but `<></>` this is null in react. Why use `null` Please elaborate more.

**Comment by drcmda** [comment]
no, for sure it is, <></> is fine, just looking kinda noisy. use that if you dont like null.

**Comment by azl397985856** [comment]
> react-dom doesn't work on node afaik, otherwise there is no difference. react-nil does nothing but allow react to run in smallest possible setup, without native elements (div, span, mesh, box, group, view, image ...). it's 20kb packed up.

it helps me a lot, thanks.
