### ISSUE TITLE
Shouldn't react be peer dependency? 

### ISSUE THREAD

**Issue by nstfkc** [react-spring/react-nil#4]
I wanted to mess around with next.js but I bumped into having two versions of react problem. Was it intended to set `react` as dependency?

**Comment by drcmda** [comment]
indeed, it packs up everything into one bundle even, probably not the best idea - will fix in a minute

**Comment by drcmda** [comment]
ive remove the dependency

**Comment by nstfkc** [comment]
Wow, thanks for the super fast response!
