### ISSUE TITLE
Uncaught TypeError: Cannot read property 'unstable_runWithPriority' of undefined

### ISSUE THREAD

**Issue by saisandeepvaddi** [react-spring/react-nil#7]
I'm trying to use this in chrome extension background script. I'm getting this error.

![image](https://user-images.githubusercontent.com/13838175/97056796-d1bb8e80-1557-11eb-8cec-6ed579805a74.png)

**Comment by saisandeepvaddi** [comment]
I used the exact same example code in the README.

**Comment by CodyJasonBennett** [comment]
Are you still getting this issue? I can't reproduce this with react 17 ([sandbox](https://codesandbox.io/s/heuristic-leftpad-pe6p6?file=/src/index.js)).

**Comment by CodyJasonBennett** [comment]
It's been two years, but have a fix for you in v1.
