### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by timoxley** [react-spring/react-nil#9]
What's the status with this project, it seems rather inactive?
Has the idea been canned or superseded by something else?

**Comment by drcmda** [comment]
there's nothing much to do i guess, it could use a dependency update maybe but the main feature is just an empty react reconciler.

**Comment by CodyJasonBennett** [comment]
We just went [`v1.0.0`](https://github.com/pmndrs/react-nil/releases/tag/v1.0.0) with support for React 18, suspense, concurrency.
